#!/bin/bash
CACHE_DIR=$HOME/.cache/configuration/slack
DEB_PACKAGE=slack-desktop-2.8.2-amd64.deb

if [ ! -d "$CACHE_DIR" ]; then
    mkdir -p "$CACHE_DIR"
fi

if command -v slack > /dev/null 2>&1; then
    echo "Slack is already installed"
    exit 0
fi

if [ ! -f "$CACHE_DIR/$DEB_PACKAGE" ]; then
    shef apt libcurl3
    shef apt gir1.2-gnomekeyring
    wget https://downloads.slack-edge.com/linux_releases/slack-desktop-2.8.2-amd64.deb -P "$CACHE_DIR"
fi

sudo dpkg -i "$CACHE_DIR/$DEB_PACKAGE"
